# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Test

on:
  push:
    branches-ignore:
      - 'renovate/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      #Checkout and setup
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'yarn'

      # Install deps
      - name: Install
        run: yarn install --frozen-lockfile

      #Build
      - name: Build
        run: yarn build

      # Run unit tests on affected apps
      - name: Run Tests
        run: yarn test
